server {
    listen 80;

    server_name php-minimal.local;

    return 301 https://$host$request_uri;
}


server {
    listen 443 ssl;

    server_name php-minimal.local;

    root /var/www/html/public;
    index index.php index.html;

    ssl_certificate /etc/nginx/certs/php-minimal.local.crt;
    ssl_certificate_key /etc/nginx/certs/php-minimal.local.key;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;

        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        include fastcgi_params;
    }
}